server:
  port: 8085
  servlet:
    context-path: /rider

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: "jdbc:mysql://localhost:3306/riderdb?useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username: "root"
    password: "root"
  jpa:
    hibernate.ddl-auto: "update"
#    hibernate.ddl-auto: "create-drop"
    show-sql: true

custom:
  places:
    - GAL
    - SHT
  shops:
    - Supermac's
    - McDonald's
    - Subway
    - Burger King
    - Papa John's